### ISSUE TITLE
CSS is lost on page navigation in static SSR with page-scoped interactive server directive

### ISSUE THREAD

**Issue by Gaz83** [gaelj/BlazorCodeMirror6#81] opened 2024-01-18 10:36 UTC
So this issue I am finding very difficult to replicate, tried in your examples and it just works fine.

Anyway, the issue.

This is all in Blazor Web App targeting .Net 8

I have the control on a page and it wall works great with theme applied etc.
Now, if I navigate to another page which also has the control on or if navigate away and come back, the control looks like it looses all css formatting i.e. you have the line numbers followed by content, all of this just stacked vertically with overflow happening, all theming loss etc.

I can't attach an example project as it's all confidential stuff and producing an example is not working.

Just wondered if you may know of something that may cause this. All other controls on the pages work fine.

Pressing F5/refresh does fix it

**Comment by Gaz83** [comment] 2024-01-18 10:37
I managed to create an example! it seems to happen if you have the control hidden and then show it after navigating.

**Comment by Gaz83** [comment] 2024-01-18 10:40
[BlazorApp1.zip](https://github.com/gaelj/BlazorCodeMirror6/files/13975464/BlazorApp1.zip)

Attached project.

Steps
Run it and use nav on left and go to Index1
Click button "Reset text" to show the Control, will have json content.
Use nav on left and go to Index2
Click button "Reset text" to show the Control which will have all styling not applied.

**Comment by gaelj** [comment] 2024-01-20 19:50
Thanks for creating an example of your issue. I will look into it.

**Comment by gaelj** [comment] 2024-01-20 23:48
The sample can be fixed by replacing,  in `App.razor`, `<HeadOutlet />` with `<HeadOutlet @rendermode="InteractiveServer" />`.

Would that be acceptable ?

**Comment by gaelj** [comment] 2024-01-21 20:30
So I confirm that the 2nd approach seems to work fine, although it could be viewed as a horrible hack.

- keep the simple `<HeadOutlet />` in `App.razor`
- start the app, do an initial load of the page with the theme you want to use
- in  browser dev tools, copy the contents of the first `style` tag
![image](https://github.com/gaelj/BlazorCodeMirror6/assets/8884632/074fe62b-5b22-43ec-a5c7-b96b4de81f9f)
- paste the contents in your apps' `wwwroot/app.css`

I cannot - for now - guarantee this won't have any other side effects, than being unable to switch themes, so I currently don't feel super comfortable with providing this CSS in the wrapper library. Of the 2, I'd recommend the first approach, if possible.

**Comment by gaelj** [comment] 2024-01-22 13:30
- That would break compatibility with WASM
- It won't change anything in the present case where you already specify with the page directive, that all components in the page should be rendered in InteractiveServer mode. The problem is that CM6 tries to modify the header of the page. The header is managed in blazor server by HeadOutlet. So if HeadOutlet isn't told that the header could change after rendering the page, it won't try to persist thoses changes on the next navigation.

**Comment by gaelj** [comment] 2024-01-25 09:13
@Gaz83 can we close this issue ? I added an example project with the new hosting model.

**Comment by gaelj** [comment] 2024-01-31 17:29
@Gaz83 feel free to reopen if needed

**Closed by gaelj** 2024-01-31 17:29 UTC

**Comment by Gaz83** [comment] 2024-02-02 09:38
@gaelj Sorry for late reply, been a bit tied up with other things in life. Yes I was happy for this to be closed, thank you.
